# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  selector:
    app: my-nginx
  type: NodePort
  ports:
  - name: my-nginx
    protocol: TCP
    port: 80 # Port auf dem der Service lauscht
    targetPort: 80  # Port auf dem der Container lauscht
    nodePort: 3001

